disabled = false
languageCode = "ua"
languageName = "Ukrainian"
weight = 1
title = "Craftmind"

[params]
  displayName = "UA üá∫üá¶"
  isoCode = "ua"
  rtl = false
  dateFormat = "02/01/2006"
  logo = "img/logo.png"
  secondaryLogo = "img/secondary-logo.png"
  description = "Craftmind"
  copyright = "–ö–æ–ø—ñ—é–π, –ø—Ä–∞–≤–∏–ª—å–Ω–æ? \U0001F914"

[params.author]
  name = "craftmind"
  email = "alexiskoval@proton.me"
  image = "img/author_logo.png"
  imageQuality = 96
  # headline = "I'm only human"
  bio = "–í–∞—à —Ö–æ–±–±—ñ –º–∞–π—Å—Ç–µ—Ä"
  links = [
    { email = "mailto:alexiskoval@proton.me" },
    { link = "https://craftmind.io/" },
#    { discord = "https://discord.gg/invitecode" },
#    { github = "https://github.com/username" },
    { instagram = "https://instagram.com/car.scale" },
#    { patreon = "https://www.patreon.com/username" },
#    { telegram = "https://t.me/username" },
    { x-twitter = "https://twitter.com/KovalAlexey" },
#    { youtube = "https://youtube.com/username" }
  ]



